# Generated by Django 4.1.3 on 2023-09-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_social", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                ("postId", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=54)),
                ("description", models.CharField(max_length=224, null=True)),
                ("dateTime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_social.socialusermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagsPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagText", models.CharField(max_length=54)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_social.postmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LikePostModel",
            fields=[
                ("likeId", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_social.postmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_social.socialusermodel",
                    ),
                ),
            ],
        ),
    ]
