# Generated by Django 4.1.3 on 2023-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_social", "0002_postmodel_tagspostmodel_likepostmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="postId",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
