# Generated by Django 4.1.3 on 2023-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_social", "0003_alter_postmodel_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="postId",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
