# Generated by Django 4.1.7 on 2023-09-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostModel",
            fields=[
                ("postId", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=54)),
                ("description", models.CharField(max_length=224, null=True)),
                ("dateTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=54)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("mobile", models.CharField(max_length=54)),
                ("username", models.CharField(max_length=54, unique=True)),
                ("password", models.CharField(max_length=54)),
            ],
        ),
        migrations.CreateModel(
            name="TagsPostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagText", models.CharField(max_length=54)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.postmodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="postmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.socialusermodel"
            ),
        ),
        migrations.CreateModel(
            name="LikePostModel",
            fields=[
                ("likeId", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.postmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.socialusermodel",
                    ),
                ),
            ],
        ),
    ]
